In [27]:
# train a linear regrssion model using Pseudo inverse of A

import numpy as np

A = [[170, 1],
     [155, 1],
     [150, 1],
     [175, 1],
     [165, 1]]

Y = [[65], [50], [45], [70], [55]]

In [28]:
At = np.transpose(A)

print(At)

[[170 155 150 175 165]
 [  1   1   1   1   1]]


In [29]:
AtA = np.dot(At,A)
AtY = np.dot(At,Y)

print(AtA)
print(AtY)

[[133275    815]
 [   815      5]]
[[46875]
 [  285]]


In [30]:
inv_AtA = np.linalg.inv(AtA)
X = np.dot(inv_AtA,AtY)

In [31]:
print(X)

[[   0.97674419]
 [-102.20930233]]
