In [1]:
# train a linear regrssion model using Pseudo inverse of A

import numpy as np

A = [[40, 30, 1],
     [30, 80, 1],
     [20, 70, 1],
     [70, 40, 1],
     [60, 20, 1]]

Z = [[1], [-1], [-1], [1], [1]]

In [2]:
At = np.transpose(A)

print(At)

[[40 30 20 70 60]
 [30 80 70 40 20]
 [ 1  1  1  1  1]]


In [4]:
AtA = np.dot(At,A)
AtZ = np.dot(At,Z)

print(AtA)
print(AtZ)

[[11400  9000   220]
 [ 9000 14200   240]
 [  220   240     5]]
[[120]
 [-60]
 [  1]]


In [5]:
inv_AtA = np.linalg.inv(AtA)
X = np.dot(inv_AtA,AtZ)

In [6]:
print(X)

[[ 0.01617647]
 [-0.03088235]
 [ 0.97058824]]
